name: Prod release # Name of the workflow

# On a push to the branch named master
on:
  push:
    branches:
      - main

# Job called build runs-on ubuntu-latest
jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout to the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      # We need to login so we can later push the image without issues.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builds devopsdockeruh/docker-hy.github.io
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          push: true
          tags: aakashgusain11/reconciliation:latest